version: '3'
services:
  app:
    container_name: yelpcamp_app 
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo_yelpcamp
    image: mongo
    ports:
      - '27018:27018'
    command: mongod --nojournal --port 27018
